services:
  web:
    build:
      context: .
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/db_schema
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_schema
    ports:
      - "5432:5432"